from flask import *
import functions
import sqlite3
import urllib

# Configuration Statements
app = Flask(__name__, template_folder="templates")
DATABASE = 'database.db'
sslContext = ('server.crt', 'server.key')

# Routes
@app.route('/', methods=['GET'])
def index():
    return render_template('/index.html', title="UEA Life | Home")

@app.route('/login', methods=['GET'])
def login():
    return render_template('/login.html', title="UEA Life | Login")

@app.route('/dashboard', methods=['GET'])
def dashboard():
    return render_template('/dashboard.html', title="UEA Life | Dashboard")

@app.route('/createPost', methods=['GET', 'POST'])
def createPost():
    return render_template('/newPost.html', title="UEA Life | Create Post")


# Function that verifies a captcha attempt by asking google whether they have verified that attempt
@app.route('/verifyCaptcha', methods=["POST", "GET"])
def verifyCaptcha():
    verifyURL = 'https://www.google.com/recaptcha/api/siteverify'
    # The secret key for this captcha generated by google
    # TODO: 11/02/2020 Need to make a new one for this project
    secret = '6Lc7ynsUAAAAAAJ4uajX9K_cSB3Vg8jdkPxzpXM7'

    # Encode the parameters required for the request
    params = urllib.parse.urlencode({
        'secret': secret,
        'response': request.form.get('g-recaptcha-response'),
    }).encode("utf-8")

    data = urllib.request.urlopen(verifyURL, params).read()
    # Google's response is a json file
    result = json.loads(data)
    # Success will either be true or false
    success = result.get('success', None)

    return success


if __name__ == '__main__':
    # TODO: 11/02/2020 Change debug to False before submitting
    # app.run(host='127.0.0.1', port=5000, debug=True, ssl_context=sslContext)
    app.run(host='127.0.0.1', port=5000, debug=True)


# Database Methods - Courtesy of Oli
def get_db():
    db = getattr(g, '_database', None)
    if db is None:
        db = g._database = sqlite3.connect(DATABASE)

    def make_dicts(cursor, row):
        return dict((cursor.description[idx][0], value)
                    for idx, value in enumerate(row))

    db.row_factory = make_dicts
    return db


def query_db(query, args=(), one=False):
    cur = None
    rv = None
    try:
        cur = get_db().execute(query, args)
        rv = cur.fetchall()
    except sqlite3.Error as e:
        app.logger.info('Database error: %s' % e)
    except Exception as e:
        app.logger.info('Exception in query_db: %s' % e)
    finally:
        if cur:
            cur.close()
    return (rv[0] if rv else None) if one else rv


@app.teardown_appcontext
def close_connection(exception):
    db = getattr(g, '_database', None)
    if db is not None:
        db.close()
